apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: workshop
  name: maiden-tiedot-kube
  labels:
    app: maiden-tiedot-kube

spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: maiden-tiedot-kube

  template:
    metadata:
      labels:
        app: maiden-tiedot-kube
      annotations:
    spec:
      containers:
        - image: gcr.io/unity-ads-workshop-test/maiden-tiedot-kube:master
          name: maiden-tiedot-kube
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 0.1
              memory: 128Mi
            limits:
              cpu: 0.5
              memory: 1024Mi
          env:
            - name: SOME_ENV_VARIABLE
              value: some env value

      nodeSelector:
        cloud.google.com/gke-nodepool: workshop-pool
