kind: Service
apiVersion: v1
metadata:
  labels:
    app: maiden_tiedot_kube
  name: maiden_tiedot_kube
  namespace: workshop

spec:
  type: NodePort
  ports:
    - name: http
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: maiden_tiedot_kube
